### ISSUE TITLE
Add coding-style chapter on assertion usage

### ISSUE THREAD

**Issue by t8m** [openssl/technical-policies#49]
There is a web pull request that can be used as a starting point: https://github.com/openssl/web/pull/42

**Comment by kroeckx** [comment]
We also have OPENSSL_assert(). All 3 are used in the code and behave differently.

**Comment by levitte** [comment]
I can't remember why we have `OPENSSL_assert()`...  I do understand `ossl_assert()` because of its return value.

Do note, though, that `ossl_assert()` is library internal and should be avoided in application code (even test programs if possible).  Why?  Because people "out there" look at our application code to get examples on how to do things.

**Comment by t8m** [comment]
We have an assert policy now.
